version: '1.0'

volumes:
  exec_data:

services:
  qc-script-redis:
    image: redis:latest
    command: --port 5010
    ports:
      - "5010:5010"
    networks:
      - default

  qc-script-splitter:
    image: stiliala/qc-script-splitter:local
    command: sh /app/startup.sh
    ports:
      - "8891:8891"
    environment:
      - REDIS_URL=redis://qc-script-redis:5010
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default

  qc-script-rq-worker:
    image: stiliala/qc-script-splitter:local
    command: rq worker --url redis://qc-script-redis:5010 qc-script-splitter
    environment:
      - REDIS_URL=redis://qc-script-redis:5010
      - DATABASE_URL=sqlite:////data/app.db
      - FLASK_RUN_HOST=qc-script-splitter
      - FLASK_RUN_PORT=8891
    volumes:
      - exec_data:/data
    depends_on:
      - qc-script-redis
    deploy:
      replicas: 1

networks:
  default:
    driver: bridge
