version: '1.0'

volumes:
  exec_data:

services:
  redis:
    image: redis:latest
    command: --port 5040
    ports:
      - "5040:5040"
    networks:
      - default

  qc-script-splitter:
    image: planqk/qc-script-splitter:local
    command: sh /app/startup.sh
    ports:
      - "1612:1612"
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default

  rq-worker:
    image: planqk/qc-script-splitter:local
    command: rq worker --url redis://redis:5040 qc-script-splitter
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
      - FLASK_RUN_HOST=qc-script-splitter
      - FLASK_RUN_PORT=1612
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 1

networks:
  default:
    driver: bridge
